### PR TITLE
Update dependencies, add FastAPI support, and enhance image publishing functionality

### PR DESCRIPTION
**Pull request by slobodaapl**
- Bump versions of `accelerate`, `aiohttp`, `win32-setctime`, and `watchfiles` in `poetry.lock`.
- Add `fastapi` as a dependency in `pyproject.toml`.
- Introduce a `debug` setting in `settings.yaml`.
- Modify `ai_api/__init__.py` to set environment variable for CI.
- Implement FastAPI app in `ai_api/main.py` and add a new endpoint for publishing images.
- Update image model to include a `public` flag and adjust database queries accordingly.
- Refactor various parts of the code for improved clarity and functionality.

### CODE REVIEW

**Review by Teebor-Choka — APPROVED** [review]
Does it fix the issue seen in the current setup?

**Comment by slobodaapl** [comment]
If you mean the issue with pydantic validation -- yes, though it was more of an oversight than a bug.

But more importantly the search functionality is modified.

**Comment by mdevecka** [comment]
I would like to clarify what is the format of data that the endpoints expect.
Previously we talked about FormData with 2 fields "image" with Blob type and "json" which would be the rest of data serialized as JSON string.
According to your latest message however you now expect multiple fields in FormData instead.
Also the same question applies to what kind of data format do you send towards backend at /ai/image/update ?
Please clarify.

**Comment by slobodaapl** [comment]
> I would like to clarify what is the format of data that the endpoints expect.
> Previously we talked about FormData with 2 fields "image" with Blob type and "json" which would be the rest of data serialized as JSON string.
> According to your latest message however you now expect multiple fields in FormData instead.
> Also the same question applies to what kind of data format do you send towards backend at /ai/image/update ?
> Please clarify.
> 
@mdevecka 

I've sent the schema in an email long ago which shows 4 fields, that is still actual. I just bumped the email where the original schema is, which also contains how I send data to the update endpoint. 

I've also replied to your most recent email with the updated schema due to enum changes, that also contains the schema from before, and the new endpoint to mark images as public

**Pull request merged**
