### PR TITLE
Refactoring, ORM update, bug fixes, JWT

### PR DESCRIPTION
**Pull request by slobodaapl**
Required actions:
- Drop all DB tables @Teebor-Choka

List of changes:
- Added JWT auth
- Fixed bugs
- Refactoring
- Changed DB schema / ORM
- Linting
- Added and updated some tests

### CODE REVIEW

**Comment by Teebor-Choka** [comment]
Build and push pipeline failing.

**Review by Teebor-Choka — APPROVED** [review]

**Comment by Teebor-Choka** [comment]
@slobodaapl if you should drop all DBs, should it not be part of your migration?

**Comment by slobodaapl** [comment]
> @slobodaapl if you should drop all DBs, should it not be part of your migration?

Usually yes, but Alembic migrations and the migration system is mainly useful and used for data integrity purposes, and data migrations. Since we haven't launched yet, and it was a prototype schema, it's simpler to just keep the revision chain for alembic clean. This is most likely the final version before we start ingesting data.

Once we have data, of course the migrations will be used.

**Comment by Teebor-Choka** [comment]
What about the failing test?

**Comment by slobodaapl** [comment]
Working on it, it's a library bug sadly, trying to work around it. Not an issue in my code

**Comment by Teebor-Choka** [comment]
> Working on it, it's a library bug sadly, trying to work around it. Not an issue in my code

I never doubted you.

**Comment by slobodaapl** [comment]
@Teebor-Choka Feel free to merge when DB tables dropped

**Pull request merged**
